### ISSUE TITLE
Css fora dos padrões de validação da w3c

### ISSUE THREAD

**Issue by ChaosAmd** [FronteiraTec/webdce#13]
Rodei os códigos de css no validador da w3c e foram encontrados 22 problemas e problemas se usado em outros navegadores, como por exemplo firefox e cerca de 324 warnings. Sugestão: Rodar um linter ao css, gerá-lo em conformidade com o padrão w3c para não ter comportamento imprevisível.

**Comment by ChaosAmd** [comment]
Também me deixo a disposição caso precisem de ajuda nesses problemas.

**Comment by fersasil** [comment]
Sei que o projeto não é a nossa prioridade, mas manter a qualidade do código é sempre bom, se puderem corrigir isso :)
